models:
  - name: STG_HCP_DTL
    columns:
      - name: hcp_npi
        tests:
          - unique
          - not_null
      # - name: status
      #   tests:
      #     - accepted_values:
      #         values: ['placed', 'shipped', 'completed', 'returned']
      # - name: customer_id
      #   tests:
      #     - relationships:
      #         to: ref('customers')
      #         field: id